version: '3.8'

services:
  telegram-bot:
    build:
      context: .  
      dockerfile: Dockerfile  
    container_name: telegram-bot-container
    volumes:
      - ./flask_app:/app/flask_app

    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    restart: unless-stopped
    working_dir: /app/flask_app    
    command: ["python", "app.py"] 
