version: '3.9'
services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=chatbot_db
      - DB_USER=chatbot_user
      - DB_PASSWORD=securepassword

  postgres:
    image: postgres:15-alpine
    container_name: chatbot_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
