services:
  telegram-bot:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: telegram-bot-container
    volumes:
      - ./flask_app:/app/flask_app
      - ./.venv:/app/.venv
    environment:
      - PYTHONUNBUFFERED=1
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env  
    ports:
      - "5000:5000"
    restart: unless-stopped
    working_dir: /app/flask_app    
    depends_on:
      - ngrok
    command: ["python", "app.py"] 
    networks:
      - conexao_apis

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN} 
      - NGROK_PORT=telegram-bot:5000
    ports:
      - "4041:4040"  # Porta para acessar o dashboard do ngrok e ver os túneis

  app:
    container_name: emergencia_node_cont
    build: ./node/
    ports:
      - ${BACKEND_PORT}:3000
    env_file:
      - ./.env
    volumes:
      - ./node/:/app/
    networks:
      - conexao_apis


networks:
  conexao_apis:
    driver: bridge
