version: '3.8'

services:
  telegram-bot:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: telegram-bot-container
    volumes:
      - ./flask_app:/app/flask_app
      - ./.venv:/app/.venv
    environment:
      - PYTHONUNBUFFERED=1
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    env_file:
      - .env  
    ports:
      - "5000:5000"
    restart: unless-stopped
    working_dir: /app/flask_app    
    depends_on:
      - ngrok
    command: ["/bin/bash", "-c", "/app/set_webhook.sh && python /app/flask_app/app.py"]

  ngrok:
    image: ngrok/ngrok
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: ["http", "telegram-bot:5000", "--hostname=civil-intimate-bedbug.ngrok-free.app"]
    ports:
      - "4041:4040"
